name       : dfmt
version    : 0.14.2
release    : 2
source     :
    - git|https://github.com/dlang-community/dfmt.git : v0.14.2
license    : BSL-1.0
component  : programming.tools
summary    : Dfmt is a formatter for D source code
description: |
    Dfmt is a formatter for D source code
networking : yes
builddeps  :
    - dmd
    - dub
    - ldc-devel
build      : |
    # NOTE: building with the makefile and ldc2 produced a borked binary
    dub build --compiler=ldc2
install    : |
    install -Dm00755 $workdir/bin/dfmt $installdir/usr/bin/dfmt
